In [1]:
from google.colab import drive
drive.mount('/content/drive')
db_root = 'drive/MyDrive/camera1_plastics_shareable_dataset'

import pandas as pd
import json

Mounted at /content/drive

## taxonomy: 15 categories of plastic

In [2]:
json_file_path = f'{db_root}/camera1_plastics_taxonomy.json'

try:
    with open(json_file_path, 'r') as f:
        data = json.load(f)

    # Assuming the JSON structure is a list of dictionaries or a dictionary of dictionaries
    # If it's a dictionary of dictionaries and you want to treat outer keys as an index or column
    if isinstance(data, dict):
        df = pd.DataFrame.from_dict(data, orient='index')
    elif isinstance(data, list):
        df = pd.DataFrame(data)
    else:
        print("JSON content is not in a recognized format for tabular display (list or dictionary).")
        df = pd.DataFrame([data]) # Try to convert as single row if it's a simple object

    display(df) # Use display for better rendering in Colab
    categories_list = df.loc['categories', 0]
    categories_df = pd.DataFrame(categories_list)
    display(categories_df)
except FileNotFoundError:
    print(f"Error: The file '{json_file_path}' was not found.")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from '{json_file_path}'. Check file content.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

                                                                              0
dataset                                                                EgoWaste
camera                                                                 Camera 1
subset_supercategory                                                   Plastics
number_of_plastic_categories                                                 15
recycle_category_options                                                     []
categories                    [{'supercategory': 'Plastics', 'name': 'Black ...

,supercategory,name,abbreviation,recycle_category,description,number_of_instances,number_of_unique_frames,number_of_gx_sequences
0,Plastics,Black Plastic Containers,Black Plastic Containers,Other Plastics,"Plastic containers, whether numbered or unnumb...",251,212,6
1,Plastics,Containers #1/Clamshells,1 Clamshell/ 1,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,493,410,6
2,Plastics,Containers #2 Colored,2 Colored,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as HDPE, ...",236,206,4
3,Plastics,Containers #2 Natural,2 Natural,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as HDPE, ...",169,137,4
4,Plastics,Containers #3-7 (Not #5),3 to 7,Other Plastic Containers,"Plastic containers that are labeled #3 PVC, #4...",130,107,5
5,Plastics,Containers #5/PP,5,Other Plastic Containers,Plastic containers that are labeled PP (polypr...,386,340,5
6,Plastics,Deposit #1 Bottles,1 Deposit,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, ...",357,294,5
7,Plastics,Garbage Bags,,Other Plastics,Disposable bag used line trash cans to hold so...,9,9,1
8,Plastics,Non-Deposit,,,,164,137,5
9,Plastics,Other #1 Bottles,1 Other,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, ...",732,631,5
10,Plastics,Other Plastic Film,Film,Other Plastics,"A thin, continuous form of plastic material of...",22,20,3
11,Plastics,Other Plastics,,Other Plastics,All remaining plastics not listed above.,223,187,6
12,Plastics,Other Rigid/Bulky Plastics,,Other Plastics,Plastics that are the size of a 5-gallon bucke...,18,16,1
13,Plastics,Other Unnumbered Containers & Fragments,Unnumbered,Other Plastic Containers,"Any loose / unnumbered plastic lids, tops, cap...",328,280,6
14,Plastics,Plastic,,,,20,18,2

In [3]:
pd.set_option('display.max_colwidth', None)
display(categories_df['description'])

0            Plastic containers, whether numbered or unnumbered, that are colored black. Excludes single-use utensils and non-container plastics.
1                          Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.
2                                                 Plastic containers that are labelled as HDPE, PEHD, or #2 that are pigmented (excluding black).
3                                                                      Plastic containers that are labelled as HDPE, PEHD, or #2 that are opaque.
4                   Plastic containers that are labeled #3 PVC, #4 LDPE, #6 PS, #7 PLA (excluding #5). Does not include EPS, even if labelled #6.
5                                                                                   Plastic containers that are labeled PP (polypropylene) or #5.
6        Plastic containers that are labelled as PETE, PET, or #1 (polyethylene terephthalate) with NY Deposit listed. Must have a screw-off lid.
7                                      Disposable bag used line trash cans to hold solid waste. Includes bathroom trash bags and contractor bags.
8
9     Plastic containers that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without NY Deposit listed. Must have a screw-off lid.
10                                                            A thin, continuous form of plastic material often used to create bags or packaging.
11                                                                                                       All remaining plastics not listed above.
12                                                                                     Plastics that are the size of a 5-gallon bucket or larger.
13                                                           Any loose / unnumbered plastic lids, tops, caps, containers, or container fragments.
14
Name: description, dtype: object

## meta_df: `frames/` & `masks/`

In [4]:
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'

try:
    meta_df = pd.read_csv(csv_file_path)
    print(f"Successfully loaded '{csv_file_path}'")
    print("\nFirst 5 rows of the DataFrame:")
    display(meta_df.head())
    print("\nDataFrame Info:")
    display(meta_df.info())
    print("\nDescriptive Statistics:")
    display(meta_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{csv_file_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

print("--- 'copied_frame_path' 컬럼 분석 ---")
display(meta_df['copied_frame_path'].describe())
print(f"'copied_frame_path' 컬럼의 결측값 수: {meta_df['copied_frame_path'].isnull().sum()}\n")

print("--- 'copied_mask_path' 컬럼 분석 ---")
display(meta_df['copied_mask_path'].describe())
print(f"'copied_mask_path' 컬럼의 결측값 수: {meta_df['copied_mask_path'].isnull().sum()}\n")

print("--- 'timestamp_clip_path' 컬럼 분석 ---")
display(meta_df['timestamp_clip_path'].describe())
print(f"'timestamp_clip_path' 컬럼의 결측값 수: {meta_df['timestamp_clip_path'].isnull().sum()}\n")

Successfully loaded 'drive/MyDrive/camera1_plastics_shareable_dataset/camera1_plastics_meta2.csv'

First 5 rows of the DataFrame:

,data_index,camera_id,gx_id,segment_id,category_name,supercategory_name,recyclable_category_name,reason,phrase,begin_time,...,_source_meta2_path,_gx_name,_camera_name,_original_row_index,frame_name_norm,object_track_id_clean,copied_frame_path,copied_mask_path,timestamp_clip_path,timestamp_transcript_phrases
0,2,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,GX010023,Camera 1,2,18,92,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000018.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX010023/GX010023__frame_000018__object_92__bd68e2a582f1.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,NaN
1,3,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,GX010023,Camera 1,3,19,92,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000019.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX010023/GX010023__frame_000019__object_92__d26f4a57caa7.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,NaN
2,4,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,GX010023,Camera 1,4,20,92,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000020.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX010023/GX010023__frame_000020__object_92__af787ef1ae72.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,NaN
3,5,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,GX010023,Camera 1,5,21,92,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000021.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX010023/GX010023__frame_000021__object_92__b6b7b1a4412a.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,NaN
4,6,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,GX010023,Camera 1,6,22,92,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000022.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX010023/GX010023__frame_000022__object_92__b405af4e51b5.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,NaN

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3538 entries, 0 to 3537
Data columns (total 96 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   data_index                         3538 non-null   int64
 1   camera_id                          3538 non-null   int64
 2   gx_id                              3538 non-null   object
 3   segment_id                         3538 non-null   int64
 4   category_name                      3538 non-null   object
 5   supercategory_name                 3538 non-null   object
 6   recyclable_category_name           3354 non-null   object
 7   reason                             3354 non-null   object
 8   phrase                             3538 non-null   object
 9   begin_time                         1916 non-null   float64
 10  end_time                           1916 non-null   float64
 11  frame_name                         3538 non-null   int64
 12  image_path                         3538 non-null   object
 13  mask_path                          3538 non-null   object
 14  object_image_path                  3538 non-null   object
 15  source_image_path                  3538 non-null   object
 16  source_mask_path                   3538 non-null   object
 17  source_object_image_path           3538 non-null   object
 18  source_side_by_side_path           1916 non-null   object
 19  hand_track_id                      1916 non-null   float64
 20  hand_side                          1916 non-null   object
 21  ml_hand_track_id                   1916 non-null   float64
 22  object_track_id                    3538 non-null   int64
 23  bbox_xywh                          3538 non-null   object
 24  rule_edge_score                    1916 non-null   float64
 25  final_edge_score                   1916 non-null   float64
 26  selection_score                    1916 non-null   float64
 27  boundary_touch_score               1916 non-null   float64
 28  contact_score                      1916 non-null   float64
 29  motion_match_score                 1916 non-null   float64
 30  object_glove_prob                  385 non-null    float64
 31  is_glove_like_object               1916 non-null   object
 32  expanded_hand_bbox                 1916 non-null   object
 33  review_status                      3538 non-null   object
 34  source_final_csv                   1916 non-null   object
 35  export_key                         3538 non-null   object
 36  side_by_side_path                  1916 non-null   object
 37  final_side_by_side_path            1916 non-null   object
 38  final_mask_path                    1916 non-null   object
 39  final_object_image_path            1916 non-null   object
 40  original_category_name             3538 non-null   object
 41  suggested_category_name            3508 non-null   object
 42  corrected_category_name            1926 non-null   object
 43  category_review_status             1926 non-null   object
 44  category_review_source             65 non-null     object
 45  mask_review_status                 1916 non-null   object
 46  delete_reason                      0 non-null      float64
 47  object_bbox                        1622 non-null   object
 48  object_centroid                    1622 non-null   object
 49  mask_archive_path                  1622 non-null   object
 50  mask_archive_key                   1622 non-null   object
 51  mask_index                         1622 non-null   float64
 52  feature_archive_path               1622 non-null   object
 53  feature_index                      1622 non-null   float64
 54  fg_feature_key                     1622 non-null   object
 55  ctx_feature_key                    1622 non-null   object
 56  concat_feature_key                 1622 non-null   object
 57  predicted_iou                      1622 non-null   float64
 58  stability_score                    1622 non-null   float64
 59  anchor_frame_name                  1622 non-null   float64
 60  anchor_object_track_id             1622 non-null   float64
 61  anchor_category_name               1622 non-null   object
 62  dino_similarity                    1622 non-null   float64
 63  size_score                         1622 non-null   float64
 64  sam_score                          1622 non-null   float64
 65  recovery_score                     1622 non-null   float64
 66  recovery_method                    1622 non-null   object
 67  comparison_path                    1622 non-null   object
 68  source_recovered_csv               1622 non-null   object
 69  source_type                        1622 non-null   object
 70  original_phrase                    3538 non-null   object
 71  category_split_candidates          3538 non-null   object
 72  category_split_source              3538 non-null   object
 73  category_split_index               3538 non-null   int64
 74  category_split_begin_time          1916 non-null   float64
 75  category_split_end_time            1916 non-null   float64
 76  frame_time_seconds                 1916 non-null   float64
 77  frame_time_source                  1916 non-null   object
 78  rare_category_review_status        17 non-null     object
 79  rare_category_review_old_category  17 non-null     object
 80  rare_category_review_new_category  17 non-null     object
 81  rare_category_review_note          17 non-null     object
 82  manual_category_override_source    65 non-null     object
 83  recycle_category                   0 non-null      float64
 84  description                        0 non-null      float64
 85  abbreviation                       0 non-null      float64
 86  _source_meta2_path                 3538 non-null   object
 87  _gx_name                           3538 non-null   object
 88  _camera_name                       3538 non-null   object
 89  _original_row_index                3538 non-null   int64
 90  frame_name_norm                    3538 non-null   int64
 91  object_track_id_clean              3538 non-null   int64
 92  copied_frame_path                  3538 non-null   object
 93  copied_mask_path                   3534 non-null   object
 94  timestamp_clip_path                1916 non-null   object
 95  timestamp_transcript_phrases       0 non-null      float64
dtypes: float64(29), int64(9), object(58)
memory usage: 2.6+ MB

None

Descriptive Statistics:

,data_index,camera_id,gx_id,segment_id,category_name,supercategory_name,recyclable_category_name,reason,phrase,begin_time,...,_source_meta2_path,_gx_name,_camera_name,_original_row_index,frame_name_norm,object_track_id_clean,copied_frame_path,copied_mask_path,timestamp_clip_path,timestamp_transcript_phrases
count,3538.000000,3538.0,3538,3538.000000,3538,3538,3354,3354,3538,1916.000000,...,3538,3538,3538,3538.000000,3538.000000,3538.000000,3538,3534,1916,0.0
unique,NaN,NaN,6,NaN,15,1,3,13,156,NaN,...,6,6,1,NaN,NaN,NaN,3002,3306,463,NaN
top,NaN,NaN,GX020023,NaN,Other #1 Bottles,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without NY Deposit listed. Must have a screw-off lid.",One non -deposit.,NaN,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX020023/data/meta2.csv,GX020023,Camera 1,NaN,NaN,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX020025/GX020025__frame_000152.jpg,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX020023/GX020023__frame_000992__object_16259__4ca091ac0a4f.png,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010025/GX010025__000800.440__000807.560.mp4,NaN
freq,NaN,NaN,1150,NaN,732,3538,1987,732,240,NaN,...,1150,1150,3538,NaN,NaN,NaN,4,2,32,NaN
mean,435.413510,1.0,NaN,81.966648,NaN,NaN,NaN,NaN,NaN,533.805538,...,NaN,NaN,NaN,435.413510,900.217637,11211.532504,NaN,NaN,NaN,NaN
std,326.108986,0.0,NaN,60.993272,NaN,NaN,NaN,NaN,NaN,294.200445,...,NaN,NaN,NaN,326.108986,646.490574,8731.674617,NaN,NaN,NaN,NaN
min,0.000000,1.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,0.000000,1.000000,4.000000,NaN,NaN,NaN,NaN
25%,169.250000,1.0,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,274.860000,...,NaN,NaN,NaN,169.250000,369.250000,4359.000000,NaN,NaN,NaN,NaN
50%,358.000000,1.0,NaN,65.000000,NaN,NaN,NaN,NaN,NaN,552.800000,...,NaN,NaN,NaN,358.000000,776.000000,8491.000000,NaN,NaN,NaN,NaN
75%,636.750000,1.0,NaN,119.000000,NaN,NaN,NaN,NaN,NaN,799.920000,...,NaN,NaN,NaN,636.750000,1324.750000,17641.000000,NaN,NaN,NaN,NaN
max,1287.000000,1.0,NaN,239.000000,NaN,NaN,NaN,NaN,NaN,1023.520000,...,NaN,NaN,NaN,1287.000000,2542.000000,31973.000000,NaN,NaN,NaN,NaN

--- 'copied_frame_path' 컬럼 분석 ---

count                                                                                                           3538
unique                                                                                                          3002
top       /media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/frames/GX020025/GX020025__frame_000152.jpg
freq                                                                                                               4
Name: copied_frame_path, dtype: object

'copied_frame_path' 컬럼의 결측값 수: 0

--- 'copied_mask_path' 컬럼 분석 ---

count                                                                                                                                      3534
unique                                                                                                                                     3306
top       /media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/masks/GX020023/GX020023__frame_000992__object_16259__4ca091ac0a4f.png
freq                                                                                                                                          2
Name: copied_mask_path, dtype: object

'copied_mask_path' 컬럼의 결측값 수: 4

--- 'timestamp_clip_path' 컬럼 분석 ---

count                                                                                                                                1916
unique                                                                                                                                463
top       /media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010025/GX010025__000800.440__000807.560.mp4
freq                                                                                                                                   32
Name: timestamp_clip_path, dtype: object

'timestamp_clip_path' 컬럼의 결측값 수: 1622

### Filecheck: all data exists

In [5]:
import os

def check_paths_in_df(df, column_name, db_root):
    print(f"--- '{column_name}' 컬럼 파일 존재 여부 확인 ---")
    if column_name not in df.columns:
        print(f"Error: Column '{column_name}' not found in DataFrame.")
        return

    unique_paths = df[column_name].dropna().unique()

    if len(unique_paths) == 0:
        print(f"No valid paths found in '{column_name}' to check.")
        return

    # Define the problematic external root and its Colab equivalent
    original_external_root = '/media/jisha/E/trash_dataset/'
    colab_equivalent_prefix = 'drive/MyDrive/'

    all_exist = True
    for path_suffix in unique_paths:
        # Step 1: Replace the old problematic absolute prefix with the new Colab-equivalent one
        if path_suffix.startswith(original_external_root):
            # Replace the external root part. Example: from /media/.../dataset_name/frames to drive/MyDrive/dataset_name/frames
            temp_path_colab_root = path_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            # If it doesn't start with the problematic prefix, assume it's already in a potentially correct format
            temp_path_colab_root = path_suffix

        # Step 2: Now, temp_path_colab_root should be like 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/...' or 'frames/...' if already relative.
        # We need to ensure the path is correctly joined with the db_root, which is 'drive/MyDrive/camera1_plastics_shareable_dataset'.
        # The `db_root` variable itself is a relative path to /content/.

        full_path_to_check = None
        # If temp_path_colab_root already contains the db_root structure, extract the relative part
        if temp_path_colab_root.startswith(db_root):
            # e.g., temp_path_colab_root = 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/...'
            # and db_root = 'drive/MyDrive/camera1_plastics_shareable_dataset'
            # We want to check 'db_root/frames/...' so we extract 'frames/...' from temp_path_colab_root
            relative_part_from_db_root = temp_path_colab_root[len(db_root):]
            # Remove leading slash if present for os.path.join
            if relative_part_from_db_root.startswith('/') or relative_part_from_db_root.startswith('\\'):
                relative_part_from_db_root = relative_part_from_db_root[1:]
            full_path_to_check = os.path.join(db_root, relative_part_from_db_root)
        else:
            # If temp_path_colab_root doesn't start with db_root, it might already be the exact path relative to /content/
            # or a path that needs to be directly joined with db_root (e.g. 'frames/GX010023/...' directly)
            full_path_to_check = os.path.join(db_root, temp_path_colab_root)

        # Ensure we are checking a non-empty path
        if not full_path_to_check:
            print(f"Warning: Could not construct a valid path for '{path_suffix}'. Skipping check.")
            all_exist = False
            continue

        if not os.path.exists(full_path_to_check):
            print(f"Warning: File does NOT exist: {full_path_to_check}")
            all_exist = False

    if all_exist:
        print(f"All {len(unique_paths)} unique files in '{column_name}' exist in '{db_root}'.")
    else:
        print(f"Some files in '{column_name}' do NOT exist in '{db_root}'. Please check warnings above.")
    print("\n")

# Check paths for each specified column
check_paths_in_df(meta_df, 'copied_frame_path', db_root)
check_paths_in_df(meta_df, 'copied_mask_path', db_root)
check_paths_in_df(meta_df, 'timestamp_clip_path', db_root)

--- 'copied_frame_path' 컬럼 파일 존재 여부 확인 ---
All 3002 unique files in 'copied_frame_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.


--- 'copied_mask_path' 컬럼 파일 존재 여부 확인 ---
All 3306 unique files in 'copied_mask_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.


--- 'timestamp_clip_path' 컬럼 파일 존재 여부 확인 ---
All 463 unique files in 'timestamp_clip_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.

### Process Frames with `detect_trash` Function

I will now create a placeholder function `detect_trash` that will simulate processing a frame and an associated video clip. Subsequently, I'll iterate through your `meta_df` to call this function for each entry, preparing for the comparison with `copied_mask_path`.

In [6]:
def detect_trash(frame_path, clip_path, expected_mask_path):
    """
    Placeholder function to simulate trash detection for a given frame.

    In the future, this function will take an image frame and potentially
    a video clip (using `clip_path`) to perform detection. The output
    will be compared with `expected_mask_path`.

    Args:
        frame_path (str): The full path to the frame image.
        clip_path (str): The full path to the video clip associated with the frame.
        expected_mask_path (str): The full path to the ground truth mask for comparison.

    Returns:
        dict: A dictionary containing simulated detection results.
              This will be expanded with actual detection results later.
    """
    # For now, simulate a result. Later, this will contain actual detection logic.
    simulated_result = {
        'frame_path': frame_path,
        'clip_path': clip_path,
        'detection_status': 'processed_simulated',
        'detected_objects': ['plastic_bottle', 'plastic_bag'], # Placeholder
        'simulated_mask_output': 'path/to/simulated_mask.png' # Placeholder
    }
    print(f"Simulating detection for frame: {os.path.basename(frame_path)} using clip: {os.path.basename(clip_path) if clip_path else 'N/A'}")
    # In a real scenario, you would run your model here, e.g.,
    # model_output = your_detection_model.predict(frame_path, video_context=clip_path)
    # comparison_result = compare_masks(model_output['mask'], expected_mask_path)

    return simulated_result

In [7]:
detection_results = []

# Set test_limit to an integer (e.g., 5) to process only the first N files.
# Set test_limit = None to process all files in meta_df.
test_limit = 5 # Change to None to process all files

if test_limit is not None:
    print(f"Processing only the first {test_limit} files for testing...")
else:
    print("Processing all files...")

# Iterate through each row of the meta_df DataFrame
for index, row in meta_df.iterrows():
    if test_limit is not None and index >= test_limit:
        print(f"Stopped after processing {test_limit} files as per test_limit.")
        break

    frame_file_suffix = row['copied_frame_path']
    mask_file_suffix = row['copied_mask_path']
    clip_file_suffix = row['timestamp_clip_path']

    # Construct full paths using db_root
    # Use the logic from check_paths_in_df to reconstruct the correct full paths
    original_external_root = '/media/jisha/E/trash_dataset/'
    colab_equivalent_prefix = 'drive/MyDrive/'

    # Process frame path
    if frame_file_suffix.startswith(original_external_root):
        frame_path_temp = frame_file_suffix.replace(original_external_root, colab_equivalent_prefix)
    else:
        frame_path_temp = frame_file_suffix

    if frame_path_temp.startswith(db_root):
        relative_part_frame = frame_path_temp[len(db_root):]
        if relative_part_frame.startswith('/') or relative_part_frame.startswith('\\'):
            relative_part_frame = relative_part_frame[1:]
        full_frame_path = os.path.join(db_root, relative_part_frame)
    else:
        full_frame_path = os.path.join(db_root, frame_path_temp)

    # Process mask path
    full_mask_path = None
    if pd.notna(mask_file_suffix):
        if mask_file_suffix.startswith(original_external_root):
            mask_path_temp = mask_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            mask_path_temp = mask_file_suffix

        if mask_path_temp.startswith(db_root):
            relative_part_mask = mask_path_temp[len(db_root):]
            if relative_part_mask.startswith('/') or relative_part_mask.startswith('\\'):
                relative_part_mask = relative_part_mask[1:]
            full_mask_path = os.path.join(db_root, relative_part_mask)
        else:
            full_mask_path = os.path.join(db_root, mask_path_temp)

    # Process clip path
    full_clip_path = None
    if pd.notna(clip_file_suffix):
        if clip_file_suffix.startswith(original_external_root):
            clip_path_temp = clip_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            clip_path_temp = clip_file_suffix

        if clip_path_temp.startswith(db_root):
            relative_part_clip = clip_path_temp[len(db_root):]
            if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
                relative_part_clip = relative_part_clip[1:]
            full_clip_path = os.path.join(db_root, relative_part_clip)
        else:
            full_clip_path = os.path.join(db_root, clip_path_temp)


    # Call the detect_trash function
    result = detect_trash(full_frame_path, full_clip_path, full_mask_path)
    detection_results.append(result)

    # Print progress during full run, or detailed for test run
    if test_limit is None and (index + 1) % 100 == 0: # Print every 100 items for full run
        print(f"Processed {index + 1} items...")
    elif test_limit is not None:
        print(f"Processed item {index+1}: {result}")

# Display summary of results
print(f"\nTotal items processed: {len(detection_results)}")
# display(pd.DataFrame(detection_results).head()) # Uncomment to see a DataFrame of results

Processing only the first 5 files for testing...
Simulating detection for frame: GX010023__frame_000018.jpg using clip: GX010023__000012.720__000014.120.mp4
Processed item 1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000018.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status': 'processed_simulated', 'detected_objects': ['plastic_bottle', 'plastic_bag'], 'simulated_mask_output': 'path/to/simulated_mask.png'}
Simulating detection for frame: GX010023__frame_000019.jpg using clip: GX010023__000012.720__000014.120.mp4
Processed item 2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000019.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status': 'processed_simulated', 'detected_objects': ['plastic_bottle', 'plastic_bag'], 'simulated_mask_output': 'path/to/simulated_mask.png'}
Simulating detection for frame: GX010023__frame_000020.jpg using clip: GX010023__000012.720__000014.120.mp4
Processed item 3: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000020.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status': 'processed_simulated', 'detected_objects': ['plastic_bottle', 'plastic_bag'], 'simulated_mask_output': 'path/to/simulated_mask.png'}
Simulating detection for frame: GX010023__frame_000021.jpg using clip: GX010023__000012.720__000014.120.mp4
Processed item 4: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000021.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status': 'processed_simulated', 'detected_objects': ['plastic_bottle', 'plastic_bag'], 'simulated_mask_output': 'path/to/simulated_mask.png'}
Simulating detection for frame: GX010023__frame_000022.jpg using clip: GX010023__000012.720__000014.120.mp4
Processed item 5: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000022.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status': 'processed_simulated', 'detected_objects': ['plastic_bottle', 'plastic_bag'], 'simulated_mask_output': 'path/to/simulated_mask.png'}
Stopped after processing 5 files as per test_limit.

Total items processed: 5

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Comparing Multiple `detect_trash` Versions

To compare different versions of your detection logic, we can define separate functions (e.g., `detect_trash_v1`, `detect_trash_v2`) and run them sequentially or in parallel for the same input. The results from each version can then be stored and analyzed.

Let's define two simulated versions of `detect_trash` and modify the processing loop to execute both, storing their outcomes in separate lists.

In [9]:
def image_load_and_test(imgNumber, testPrompt ):
    imagePath = f"/content/drive/MyDrive/plastics_dataset/frames/GX010023/GX010023__frame_{imgNumber}.jpg"
    imgTest = Image.open(imagePath)

    processor = Sam3Processor(model, confidence_threshold=0.5)
    inference_state = processor.set_image(imgTest)
    # 텍스트로 객체 찾기
    processor.reset_all_prompts(inference_state)
    inference_state = processor.set_text_prompt(state=inference_state, prompt=testPrompt)

    print(inference_state.keys())
    print(inference_state["boxes"])
    boxes = inference_state["boxes"]

    plot_results(imgTest, inference_state)

def detect_trash_v1(frame_path, clip_path, expected_mask_path):
    imgTest = Image.open(frame_path)


    simulated_result = {
        'frame_path': frame_path,
        'clip_path': clip_path,
        'detection_status_v1': 'processed_by_v1',
        'detected_objects_v1': ['plastic_bottle', 'can'],
        'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png' # Placeholder
    }
    # print(f"Simulating V1 detection for frame: {os.path.basename(frame_path)}")
    return simulated_result

def detect_trash_v2(frame_path, clip_path, expected_mask_path):
    """
    Simulated Version 2 of the trash detection function.
    """
    simulated_result = {
        'frame_path': frame_path,
        'clip_path': clip_path,
        'detection_status_v2': 'processed_by_v2',
        'detected_objects_v2': ['plastic_bag', 'glass_bottle'],
        'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png' # Placeholder
    }
    # print(f"Simulating V2 detection for frame: {os.path.basename(frame_path)}")
    return simulated_result

In [10]:
from PIL import Image


detection_results_v1 = []
detection_results_v2 = []

# Set test_limit to an integer (e.g., 5) to process only the first N files.
# Set test_limit = None to process all files in meta_df.
test_limit = 5 # Change to None to process all files

if test_limit is not None:
    print(f"Processing only the first {test_limit} files for testing...")
else:
    print("Processing all files...")

# Iterate through each row of the meta_df DataFrame
for index, row in meta_df.iterrows():
    if test_limit is not None and index >= test_limit:
        print(f"Stopped after processing {test_limit} files as per test_limit.")
        break

    frame_file_suffix = row['copied_frame_path']
    mask_file_suffix = row['copied_mask_path']
    clip_file_suffix = row['timestamp_clip_path']

    # Construct full paths using db_root
    original_external_root = '/media/jisha/E/trash_dataset/'
    colab_equivalent_prefix = 'drive/MyDrive/'

    # Process frame path
    if frame_file_suffix.startswith(original_external_root):
        frame_path_temp = frame_file_suffix.replace(original_external_root, colab_equivalent_prefix)
    else:
        frame_path_temp = frame_file_suffix

    if frame_path_temp.startswith(db_root):
        relative_part_frame = frame_path_temp[len(db_root):]
        if relative_part_frame.startswith('/') or relative_part_frame.startswith('\\'):
            relative_part_frame = relative_part_frame[1:]
        full_frame_path = os.path.join(db_root, relative_part_frame)
    else:
        full_frame_path = os.path.join(db_root, frame_path_temp)

    # Process mask path
    full_mask_path = None
    if pd.notna(mask_file_suffix):
        if mask_file_suffix.startswith(original_external_root):
            mask_path_temp = mask_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            mask_path_temp = mask_file_suffix

        if mask_path_temp.startswith(db_root):
            relative_part_mask = mask_path_temp[len(db_root):]
            if relative_part_mask.startswith('/') or relative_part_mask.startswith('\\'):
                relative_part_mask = relative_part_mask[1:]
            full_mask_path = os.path.join(db_root, relative_part_mask)
        else:
            full_mask_path = os.path.join(db_root, mask_path_temp)

    # Process clip path
    full_clip_path = None
    if pd.notna(clip_file_suffix):
        if clip_file_suffix.startswith(original_external_root):
            clip_path_temp = clip_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            clip_path_temp = clip_file_suffix

        if clip_path_temp.startswith(db_root):
            relative_part_clip = clip_path_temp[len(db_root):]
            if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
                relative_part_clip = relative_part_clip[1:]
            full_clip_path = os.path.join(db_root, relative_part_clip)
        else:
            full_clip_path = os.path.join(db_root, clip_path_temp)

    # Call both versions of the detect_trash function
    result_v1 = detect_trash_v1(full_frame_path, full_clip_path, full_mask_path)
    result_v2 = detect_trash_v2(full_frame_path, full_clip_path, full_mask_path)

    detection_results_v1.append(result_v1)
    detection_results_v2.append(result_v2)

    # Print progress
    if test_limit is None and (index + 1) % 100 == 0:
        print(f"Processed {index + 1} items...")
    elif test_limit is not None:
        print(f"Processed item {index+1} with V1: {result_v1}")
        print(f"Processed item {index+1} with V2: {result_v2}")

if test_limit is not None:
    print(f"Stopped after processing {len(detection_results_v1)} files as per test_limit.")

# Display summary of results
print(f"\nTotal items processed by V1: {len(detection_results_v1)}")
print(f"Total items processed by V2: {len(detection_results_v2)}")

# To see the results, you can uncomment these lines:
# display(pd.DataFrame(detection_results_v1).head())
# display(pd.DataFrame(detection_results_v2).head())

Processing only the first 5 files for testing...
Processed item 1 with V1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000018.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v1': 'processed_by_v1', 'detected_objects_v1': ['plastic_bottle', 'can'], 'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png'}
Processed item 1 with V2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000018.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v2': 'processed_by_v2', 'detected_objects_v2': ['plastic_bag', 'glass_bottle'], 'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png'}
Processed item 2 with V1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000019.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v1': 'processed_by_v1', 'detected_objects_v1': ['plastic_bottle', 'can'], 'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png'}
Processed item 2 with V2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000019.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v2': 'processed_by_v2', 'detected_objects_v2': ['plastic_bag', 'glass_bottle'], 'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png'}
Processed item 3 with V1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000020.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v1': 'processed_by_v1', 'detected_objects_v1': ['plastic_bottle', 'can'], 'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png'}
Processed item 3 with V2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000020.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v2': 'processed_by_v2', 'detected_objects_v2': ['plastic_bag', 'glass_bottle'], 'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png'}
Processed item 4 with V1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000021.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v1': 'processed_by_v1', 'detected_objects_v1': ['plastic_bottle', 'can'], 'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png'}
Processed item 4 with V2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000021.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v2': 'processed_by_v2', 'detected_objects_v2': ['plastic_bag', 'glass_bottle'], 'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png'}
Processed item 5 with V1: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000022.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v1': 'processed_by_v1', 'detected_objects_v1': ['plastic_bottle', 'can'], 'simulated_mask_output_v1': 'path/to/simulated_mask_v1.png'}
Processed item 5 with V2: {'frame_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/GX010023/GX010023__frame_000022.jpg', 'clip_path': 'drive/MyDrive/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4', 'detection_status_v2': 'processed_by_v2', 'detected_objects_v2': ['plastic_bag', 'glass_bottle'], 'simulated_mask_output_v2': 'path/to/simulated_mask_v2.png'}
Stopped after processing 5 files as per test_limit.
Stopped after processing 5 files as per test_limit.

Total items processed by V1: 5
Total items processed by V2: 5

## Extracting Audio from Video Clips

Now, I will extract the audio from the video files listed in the `timestamp_clip_path` column. The extracted audio files will be saved in the `/content/audio` directory. I'll use `moviepy` for this task.

In [11]:
# Install moviepy if not already installed
!pip install moviepy

import os
from moviepy.editor import VideoFileClip

# Create the directory for saving audio files if it doesn't exist
audio_output_dir = '/content/audio'
os.makedirs(audio_output_dir, exist_ok=True)
print(f"Audio output directory '{audio_output_dir}' ensured.")

Requirement already satisfied: moviepy in /usr/local/lib/python3.12/dist-packages (1.0.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /usr/local/lib/python3.12/dist-packages (from moviepy) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /usr/local/lib/python3.12/dist-packages (from moviepy) (4.67.3)
Requirement already satisfied: requests<3.0,>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from moviepy) (2.32.4)
Requirement already satisfied: proglog<=1.0.0 in /usr/local/lib/python3.12/dist-packages (from moviepy) (0.1.12)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.12/dist-packages (from moviepy) (2.0.2)
Requirement already satisfied: imageio<3.0,>=2.5 in /usr/local/lib/python3.12/dist-packages (from moviepy) (2.37.3)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from moviepy) (0.6.0)
Requirement already satisfied: pillow>=8.3.2 in /usr/local/lib/python3.12/dist-packages (from imageio<3.0,>=2.5->moviepy) (11.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.8.1->moviepy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.8.1->moviepy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.8.1->moviepy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.8.1->moviepy) (2026.6.17)

/usr/local/lib/python3.12/dist-packages/moviepy/config_defaults.py:47: SyntaxWarning: invalid escape sequence '\P'
  IMAGEMAGICK_BINARY = r"C:\Program Files\ImageMagick-6.8.8-Q16\magick.exe"
/usr/local/lib/python3.12/dist-packages/moviepy/video/io/ffmpeg_reader.py:294: SyntaxWarning: invalid escape sequence '\d'
  lines_video = [l for l in lines if ' Video: ' in l and re.search('\d+x\d+', l)]
/usr/local/lib/python3.12/dist-packages/moviepy/video/io/ffmpeg_reader.py:367: SyntaxWarning: invalid escape sequence '\d'
  rotation_lines = [l for l in lines if 'rotate          :' in l and re.search('\d+$', l)]
/usr/local/lib/python3.12/dist-packages/moviepy/video/io/ffmpeg_reader.py:370: SyntaxWarning: invalid escape sequence '\d'
  match = re.search('\d+$', rotation_line)
WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/moviepy/video/io/sliders.py:61: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if event.key is 'enter':

Audio output directory '/content/audio' ensured.

In [12]:
extracted_audio_info = []

# Set test_limit to an integer (e.g., 5) to process only the first N files.
# Set test_limit = None to process all files in meta_df.
test_limit = None # Change to None to process all files

test_limit = 5

if test_limit is not None:
    print(f"Processing only the first {test_limit} video clips for audio extraction...")
else:
    print("Processing all video clips for audio extraction...")

# Import tqdm for progress bar
from tqdm.notebook import tqdm

# Iterate through each row of the meta_df DataFrame with tqdm
# For rows where 'timestamp_clip_path' is NaN, we pass None for clip_path
for index, row in tqdm(meta_df.iterrows(), total=len(meta_df) if test_limit is None else test_limit):
    if test_limit is not None and index >= test_limit:
        print(f"Stopped after processing {test_limit} video clips as per test_limit.")
        break

    clip_file_suffix = row['timestamp_clip_path']

    # Only process if clip_file_suffix is not NaN
    if pd.notna(clip_file_suffix):
        # Construct full video path using the established remapping logic
        original_external_root = '/media/jisha/E/trash_dataset/'
        colab_equivalent_prefix = 'drive/MyDrive/'

        if clip_file_suffix.startswith(original_external_root):
            clip_path_temp = clip_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            clip_path_temp = clip_file_suffix

        if clip_path_temp.startswith(db_root):
            relative_part_clip = clip_path_temp[len(db_root):]
            if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
                relative_part_clip = relative_part_clip[1:]
            full_video_path = os.path.join(db_root, relative_part_clip)
        else:
            full_video_path = os.path.join(db_root, clip_path_temp)

        # Construct output audio file path
        video_basename = os.path.basename(full_video_path)
        audio_filename = os.path.splitext(video_basename)[0] + '.mp3' # or .wav
        output_audio_path = os.path.join(audio_output_dir, audio_filename)

        try:
            if os.path.exists(full_video_path):
                # print(f"Extracting audio from: {full_video_path}") # Suppress this for cleaner tqdm output
                video = VideoFileClip(full_video_path)
                if video.audio is not None:
                    video.audio.write_audiofile(output_audio_path, logger=None) # logger=None to suppress moviepy verbose output
                    extracted_audio_info.append({
                        'original_video_path': full_video_path,
                        'extracted_audio_path': output_audio_path,
                        'status': 'success'
                    })
                    # print(f"Audio saved to: {output_audio_path}") # Suppress this for cleaner tqdm output
                else:
                    extracted_audio_info.append({
                        'original_video_path': full_video_path,
                        'extracted_audio_path': None,
                        'status': 'no_audio_track'
                    })
                    print(f"Warning: No audio track found in {full_video_path}")
                video.close() # Close the video file
            else:
                extracted_audio_info.append({
                    'original_video_path': full_video_path,
                    'extracted_audio_path': None,
                    'status': 'video_not_found'
                })
                print(f"Error: Video file not found: {full_video_path}")

        except Exception as e:
            extracted_audio_info.append({
                'original_video_path': full_video_path,
                'extracted_audio_path': None,
                'status': f'error: {e}'
            })
            print(f"Error extracting audio from {full_video_path}: {e}")
    else:
        # Handle cases where 'timestamp_clip_path' is NaN
        extracted_audio_info.append({
            'original_video_path': None,
            'extracted_audio_path': None,
            'status': 'no_clip_path'
        })

print(f"\nTotal video clips processed for audio extraction: {len(extracted_audio_info)}")
# To see the results, uncomment the line below:
# display(pd.DataFrame(extracted_audio_info).head())

!mv /content/audio /content/drive/MyDrive/csire_code/audio

Processing only the first 5 video clips for audio extraction...

  0%|          | 0/5 [00:00<?, ?it/s]

Stopped after processing 5 video clips as per test_limit.

Total video clips processed for audio extraction: 5
mv: inter-device move failed: '/content/audio' to '/content/drive/MyDrive/csire_code/audio/audio'; unable to remove target: Directory not empty

In [13]:
!du -hs /content/drive/MyDrive/csire_code/audio

35M	/content/drive/MyDrive/csire_code/audio

In [14]:
!ls -al /content/drive/MyDrive/csire_code/audio | wc

    465    4178   37101

### Audio Transcription using Whisper

First, I will install the `openai-whisper` library, which is a state-of-the-art automatic speech recognition (ASR) system. It also requires `torch` for GPU acceleration and `ffmpeg` for audio processing (which should already be available from `moviepy` installation).

In [15]:
# Install Whisper and other necessary libraries if they aren't already
!pip install -qqq openai-whisper

import os
import json
import pandas as pd
import whisper
from tqdm.notebook import tqdm
from datetime import datetime

print("Whisper and other libraries imported.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 11.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for openai-whisper (pyproject.toml) ... done
Whisper and other libraries imported.

Next, I will define the input and output directories and ensure the output directory for transcriptions exists.

In [16]:
audio_input_dir = '/content/drive/MyDrive/csire_code/audio'
transcribe_output_dir = '/content/drive/MyDrive/csire_code/transcribe/v1'
manifest_output_path = '/content/drive/MyDrive/csire_code/transcribe/manifest_v1.json'

os.makedirs(transcribe_output_dir, exist_ok=True)
os.makedirs(os.path.dirname(manifest_output_path), exist_ok=True)

print(f"Audio input directory: {audio_input_dir}")
print(f"Transcription output directory: {transcribe_output_dir}")
print(f"Manifest output path: {manifest_output_path}")

Audio input directory: /content/drive/MyDrive/csire_code/audio
Transcription output directory: /content/drive/MyDrive/csire_code/transcribe/v1
Manifest output path: /content/drive/MyDrive/csire_code/transcribe/manifest_v1.json

Now, I will load the Whisper model (using the 'base' model as a default, but you can change this to 'small', 'medium', or 'large' depending on your needs and available resources). Then, I'll iterate through all audio files in the input directory, transcribe them, and save the results as text files. A manifest file will also be created to log the transcription details.

In [ ]:
# Load the Whisper model
# You can choose 'tiny', 'base', 'small', 'medium', 'large'
# Larger models offer better accuracy but require more VRAM and take longer.
print("Loading Whisper model...")
model = whisper.load_model("base")
print("Whisper model loaded.")

transcription_results = []

# Get list of audio files
audio_files = [f for f in os.listdir(audio_input_dir) if f.endswith('.mp3')]

print(f"Found {len(audio_files)} audio files to transcribe.")

for audio_filename in tqdm(audio_files, desc="Transcribing audio files"):
    audio_file_path = os.path.join(audio_input_dir, audio_filename)
    output_txt_filename = os.path.splitext(audio_filename)[0] + '.txt'
    output_txt_path = os.path.join(transcribe_output_dir, output_txt_filename)

    try:
        # Transcribe the audio
        result = model.transcribe(audio_file_path)
        transcription_text = result["text"]

        # Save the transcription to a text file
        with open(output_txt_path, 'w', encoding='utf-8') as f:
            f.write(transcription_text)

        transcription_results.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': output_txt_path,
            'status': 'success',
            'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
        })
    except Exception as e:
        transcription_results.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': None,
            'status': f'error: {e}',
            'transcription_text_snippet': None
        })
        print(f"Error transcribing {audio_filename}: {e}")

print(f"\nCompleted transcription for {len(transcription_results)} files.")

Loading Whisper model...

100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 169MiB/s]

Whisper model loaded.
Found 463 audio files to transcribe.

Transcribing audio files:   0%|          | 0/463 [00:00<?, ?it/s]

Completed transcription for 463 files.

Finally, I will create a manifest file `manifest_v1.json` containing the details of this transcription run, including the model used, timestamp, and a summary of each transcribed file.

In [ ]:
# Create the manifest file
manifest_data = {
    'run_timestamp': datetime.now().isoformat(),
    'whisper_model': 'base', # Ensure this matches the model used above
    'audio_input_directory': audio_input_dir,
    'transcription_output_directory': transcribe_output_dir,
    'transcription_summary': transcription_results
}

with open(manifest_output_path, 'w', encoding='utf-8') as f:
    json.dump(manifest_data, f, ensure_ascii=False, indent=4)

print(f"Manifest file saved to: {manifest_output_path}")

# Display a snippet of the manifest for verification
print("\nManifest file content (first 5 entries):")
with open(manifest_output_path, 'r', encoding='utf-8') as f:
    manifest_content = json.load(f)
display(pd.DataFrame(manifest_content['transcription_summary']).head())

Manifest file saved to: /content/drive/MyDrive/csire_code/transcribe/manifest_v1.json

Manifest file content (first 5 entries):

,audio_filename,audio_path,transcription_path,status,transcription_text_snippet
0,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.
1,GX010023__000099.020__000099.840.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000099.020__000099.840.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000099.020__000099.840.txt,success,あなた's throw. 1941. 一種流行
2,GX010023__000174.060__000174.680.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000174.060__000174.680.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000174.060__000174.680.txt,success,plastic clamshell
3,GX010023__000177.480__000177.860.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000177.480__000177.860.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000177.480__000177.860.txt,success,So... flamsetliles
4,GX010023__000226.500__000226.940.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000226.500__000226.940.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000226.500__000226.940.txt,success,Dance show!

## 전사 결과와 `camera1_plastics_timestamp_groups.csv` 비교

`camera1_plastics_timestamp_groups.csv` 파일의 정보를 활용하여 Whisper 전사 결과를 비교하려면, 두 데이터 간의 연결 고리를 찾아야 합니다. 일반적으로는 영상 클립의 이름, 시간 정보 또는 고유 ID 등이 연결 고리가 될 수 있습니다.

먼저, `camera1_plastics_timestamp_groups.csv` 파일을 로드하고 그 내용을 살펴보겠습니다.

In [ ]:
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'

try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    print(f"Successfully loaded '{timestamp_groups_csv_path}'")
    print("\nFirst 5 rows of the DataFrame:")
    display(timestamp_groups_df.head())
    print("\nDataFrame Info:")
    display(timestamp_groups_df.info())
    print("\nDescriptive Statistics:")
    display(timestamp_groups_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{timestamp_groups_csv_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Successfully loaded 'drive/MyDrive/camera1_plastics_shareable_dataset/camera1_plastics_timestamp_groups.csv'

First 5 rows of the DataFrame:

,gx_name,source_meta2_path,begin_time,end_time,duration_seconds,meta2_phrase,transcript_phrases,category_names,supercategory_names,number_of_meta2_rows,number_of_unique_frames,start_frame,end_frame,frame_names,raw_video_path,transcript_json_path,clip_path,clip_status
0,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,10.62,12.02,1.40,Unnumbered.,NaN,Other Unnumbered Containers & Fragments,Plastics,10,7,2,10,000002 | 000003 | 000005 | 000007 | 000008 | 000009 | 000010,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000010.620__000012.020.mp4,created
1,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,12.72,14.12,1.40,Clamshell.,NaN,Containers #1/Clamshells,Plastics,5,5,18,22,000018 | 000019 | 000020 | 000021 | 000022,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,created
2,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,15.00,20.26,5.26,Number 5.,NaN,Containers #5/PP,Plastics,5,4,48,64,000048 | 000062 | 000063 | 000064,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000015.000__000020.260.mp4,created
3,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,32.46,33.50,1.04,Two color.,NaN,Containers #2 Colored,Plastics,11,7,89,95,000089 | 000090 | 000091 | 000092 | 000093 | 000094 | 000095,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000032.460__000033.500.mp4,created
4,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,46.62,47.44,0.82,Two color.,NaN,Containers #2 Colored,Plastics,6,5,97,102,000097 | 000098 | 000099 | 000100 | 000102,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000046.620__000047.440.mp4,created

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gx_name                  463 non-null    object
 1   source_meta2_path        463 non-null    object
 2   begin_time               463 non-null    float64
 3   end_time                 463 non-null    float64
 4   duration_seconds         463 non-null    float64
 5   meta2_phrase             463 non-null    object
 6   transcript_phrases       0 non-null      float64
 7   category_names           463 non-null    object
 8   supercategory_names      463 non-null    object
 9   number_of_meta2_rows     463 non-null    int64
 10  number_of_unique_frames  463 non-null    int64
 11  start_frame              463 non-null    int64
 12  end_frame                463 non-null    int64
 13  frame_names              463 non-null    object
 14  raw_video_path           463 non-null    object
 15  transcript_json_path     0 non-null      float64
 16  clip_path                463 non-null    object
 17  clip_status              463 non-null    object
dtypes: float64(5), int64(4), object(9)
memory usage: 65.2+ KB

None

Descriptive Statistics:

,gx_name,source_meta2_path,begin_time,end_time,duration_seconds,meta2_phrase,transcript_phrases,category_names,supercategory_names,number_of_meta2_rows,number_of_unique_frames,start_frame,end_frame,frame_names,raw_video_path,transcript_json_path,clip_path,clip_status
count,463,463,463.000000,463.000000,463.000000,463,0.0,463,463,463.000000,463.000000,463.000000,463.000000,463,463,0.0,463,463
unique,6,6,NaN,NaN,NaN,156,NaN,20,1,NaN,NaN,NaN,NaN,459,6,NaN,463,1
top,GX020023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX020023/data/meta2.csv,NaN,NaN,NaN,Clamshell.,NaN,Other #1 Bottles,Plastics,NaN,NaN,NaN,NaN,001970 | 001971,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX020023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX030023/GX030023__000180.640__000181.240.mp4,created
freq,143,143,NaN,NaN,NaN,33,NaN,81,463,NaN,NaN,NaN,NaN,2,143,NaN,1,463
mean,NaN,NaN,539.531382,540.864190,1.332808,NaN,NaN,NaN,NaN,4.138229,3.542117,939.181425,943.161987,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,297.876017,297.925318,1.015753,NaN,NaN,NaN,NaN,3.801672,3.059627,678.553502,678.110497,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,1.320000,0.220000,NaN,NaN,NaN,NaN,1.000000,1.000000,2.000000,8.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,270.410000,271.530000,0.710000,NaN,NaN,NaN,NaN,2.000000,1.000000,351.000000,356.500000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,573.840000,577.200000,1.060000,NaN,NaN,NaN,NaN,3.000000,3.000000,845.000000,845.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,793.140000,795.170000,1.560000,NaN,NaN,NaN,NaN,6.000000,5.000000,1364.000000,1365.500000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,1023.520000,1024.600000,7.880000,NaN,NaN,NaN,NaN,32.000000,27.000000,2542.000000,2542.000000,NaN,NaN,NaN,NaN,NaN

이제 `timestamp_groups_df`를 로드했으니, 이 데이터프레임과 `meta_df`, 그리고 전사 결과를 연결할 수 있는 방법을 찾아야 합니다. `audio_filename`은 `timestamp_clip_path`에서 파생되었으므로, 이 두 컬럼과 `timestamp_groups_df`의 관련 컬럼을 비교하여 연결점을 찾아보겠습니다.

`timestamp_groups_df`의 `clip_path`와 `meta_df`의 `timestamp_clip_path`가 유사한 형식임을 알 수 있습니다. 이들을 매핑하여 전사 결과를 그룹화된 타임스탬프 정보와 연결할 수 있습니다. 예를 들어, 특정 비디오 클립에 대한 전사 내용과 해당 클립의 `phrase`나 `reason` 등을 비교할 수 있습니다.

In [ ]:
import pandas as pd # Ensure pandas is imported if not already in scope
import os # Ensure os is imported if not already in scope

# Ensure meta_df is loaded. This is necessary if previous cells defining it were not run.
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'
try:
    meta_df = pd.read_csv(csv_file_path)
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' for meta_df was not found.")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading meta_df: {e}")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors

# Ensure timestamp_groups_df is loaded. This is necessary if previous cells defining it were not run.
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors


# manifest_v1.json 파일을 다시 로드하는 대신, 이미 메모리에 있는 transcription_results 변수를 사용합니다.
transcription_df = pd.DataFrame(transcription_results)

# 'audio_filename'에서 clip ID를 추출 (예: 'GX010023__000012.720__000014.120.mp3' -> 'GX010023__000012.720__000014.120')
transcription_df['clip_id'] = transcription_df['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# meta_df의 'timestamp_clip_path'에서 clip ID 추출
# 기존의 remapping 로직을 사용하여 'timestamp_clip_path'를 정규화된 형태로 만든 후 clip ID를 추출합니다.
original_external_root = '/media/jisha/E/trash_dataset/'
colab_equivalent_prefix = 'drive/MyDrive/'

def get_normalized_clip_id(clip_path_suffix):
    if pd.isna(clip_path_suffix): return None

    # Step 1: Replace the old problematic absolute prefix
    if clip_path_suffix.startswith(original_external_root):
        clip_path_temp = clip_path_suffix.replace(original_external_root, colab_equivalent_prefix)
    else:
        clip_path_temp = clip_path_suffix

    # Step 2: Extract the relevant part after db_root (if present) or use as is
    if clip_path_temp.startswith(db_root):
        relative_part_clip = clip_path_temp[len(db_root):]
        if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
            relative_part_clip = relative_part_clip[1:]
        # Now, relative_part_clip should look like 'audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4'
        # We need to get just the filename part, then remove extension
        return os.path.splitext(os.path.basename(relative_part_clip))[0]
    else:
        # If it doesn't start with db_root, assume it's already a relative path or direct filename
        return os.path.splitext(os.path.basename(clip_path_temp))[0]

meta_df['normalized_clip_id'] = meta_df['timestamp_clip_path'].apply(get_normalized_clip_id)

# timestamp_groups_df의 'clip_path'에서 clip ID 추출
# 'clip_path' 컬럼이 이미 상대 경로 또는 파일 이름 형식일 것이므로, 바로 확장자를 제거합니다.
timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)


# 이제 transcription_df와 timestamp_groups_df를 'clip_id'를 기준으로 병합하여 비교할 수 있습니다.
# meta_df의 정보를 포함하여 더 풍부한 비교를 할 수도 있습니다.

# transcription_df와 meta_df 병합
merged_transcriptions = pd.merge(
    transcription_df,
    meta_df[['normalized_clip_id', 'phrase', 'reason', 'category_name', 'supercategory_name']],
    left_on='clip_id',
    right_on='normalized_clip_id',
    how='left'
)

# 병합된 결과에 timestamp_groups_df 정보 추가
final_comparison_df = pd.merge(
    merged_transcriptions,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'begin_time', 'end_time']].rename(columns={'meta2_phrase': 'timestamp_group_phrase'}),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

print("\nMerged DataFrame for comparison (first 5 rows):")
display(final_comparison_df.head())

print("\nColumns available for comparison:")
print(final_comparison_df.columns.tolist())

print("\n비교 아이디어:")
print("1. 'transcription_text_snippet'과 'phrase' 또는 'timestamp_group_phrase'를 비교하여 키워드 일치 여부 확인")
print("2. 'category_name', 'supercategory_name'과 'transcription_text_snippet'의 관련성 분석")
print("3. 특정 키워드가 포함된 전사 내용을 기준으로 데이터 필터링")

Merged DataFrame for comparison (first 5 rows):

,audio_filename,audio_path,transcription_path,status,transcription_text_snippet,clip_id,normalized_clip_id,phrase,reason,category_name,supercategory_name,timestamp_group_phrase,begin_time,end_time
0,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.,GX010023__000012.720__000014.120,GX010023__000012.720__000014.120,Clamshell.,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Containers #1/Clamshells,Plastics,Clamshell.,12.72,14.12
1,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.,GX010023__000012.720__000014.120,GX010023__000012.720__000014.120,Clamshell.,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Containers #1/Clamshells,Plastics,Clamshell.,12.72,14.12
2,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.,GX010023__000012.720__000014.120,GX010023__000012.720__000014.120,Clamshell.,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Containers #1/Clamshells,Plastics,Clamshell.,12.72,14.12
3,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.,GX010023__000012.720__000014.120,GX010023__000012.720__000014.120,Clamshell.,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Containers #1/Clamshells,Plastics,Clamshell.,12.72,14.12
4,GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/audio/GX010023__000012.720__000014.120.mp3,/content/drive/MyDrive/csire_code/transcribe/v1/GX010023__000012.720__000014.120.txt,success,Unnumbered. Fire'm show.,GX010023__000012.720__000014.120,GX010023__000012.720__000014.120,Clamshell.,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid.",Containers #1/Clamshells,Plastics,Clamshell.,12.72,14.12

Columns available for comparison:
['audio_filename', 'audio_path', 'transcription_path', 'status', 'transcription_text_snippet', 'clip_id', 'normalized_clip_id', 'phrase', 'reason', 'category_name', 'supercategory_name', 'timestamp_group_phrase', 'begin_time', 'end_time']

비교 아이디어:
1. 'transcription_text_snippet'과 'phrase' 또는 'timestamp_group_phrase'를 비교하여 키워드 일치 여부 확인
2. 'category_name', 'supercategory_name'과 'transcription_text_snippet'의 관련성 분석
3. 특정 키워드가 포함된 전사 내용을 기준으로 데이터 필터링

### 전사 결과와 기존 메타데이터의 'phrase' 비교

이제 `final_comparison_df`를 활용하여 Whisper 전사 (`transcription_text_snippet`) 내용과 `meta_df`의 `phrase` 및 `timestamp_groups_df`의 `timestamp_group_phrase` 간의 일치 여부를 비교해 보겠습니다. 주로 키워드 포함 여부를 확인하는 방식으로 진행합니다.

In [ ]:
# 텍스트 스니펫과 구문 간의 키워드 일치 여부를 확인하는 함수
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    # 소문자로 변환하여 비교하고, 띄어쓰기를 기준으로 단어 분리 (간단한 형태)
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())

    # 전사된 텍스트의 단어가 target_phrase의 단어에 하나라도 포함되면 True
    return bool(transcription_words.intersection(target_words))

# 'transcription_text_snippet'과 'phrase' 간의 일치 여부 확인
final_comparison_df['matches_meta_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# 'transcription_text_snippet'과 'timestamp_group_phrase' 간의 일치 여부 확인
final_comparison_df['matches_timestamp_group_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['timestamp_group_phrase']),
    axis=1
)

print("키워드 매칭 결과 (상위 10개):")
display(final_comparison_df[['audio_filename', 'transcription_text_snippet', 'phrase', 'matches_meta_phrase', 'timestamp_group_phrase', 'matches_timestamp_group_phrase']].head(10))

print("\n'phrase'와 매칭된 전사 비율:")
print(f"{final_comparison_df['matches_meta_phrase'].sum() / len(final_comparison_df):.2%}")

print("\n'timestamp_group_phrase'와 매칭된 전사 비율:")
print(f"{final_comparison_df['matches_timestamp_group_phrase'].sum() / len(final_comparison_df):.2%}")

키워드 매칭 결과 (상위 10개):

,audio_filename,transcription_text_snippet,phrase,matches_meta_phrase,timestamp_group_phrase,matches_timestamp_group_phrase
0,GX010023__000012.720__000014.120.mp3,Unnumbered. Fire'm show.,Clamshell.,False,Clamshell.,False
1,GX010023__000012.720__000014.120.mp3,Unnumbered. Fire'm show.,Clamshell.,False,Clamshell.,False
2,GX010023__000012.720__000014.120.mp3,Unnumbered. Fire'm show.,Clamshell.,False,Clamshell.,False
3,GX010023__000012.720__000014.120.mp3,Unnumbered. Fire'm show.,Clamshell.,False,Clamshell.,False
4,GX010023__000012.720__000014.120.mp3,Unnumbered. Fire'm show.,Clamshell.,False,Clamshell.,False
5,GX010023__000099.020__000099.840.mp3,あなた's throw. 1941. 一種流行,One clamshell.,False,One clamshell.,False
6,GX010023__000099.020__000099.840.mp3,あなた's throw. 1941. 一種流行,One clamshell.,False,One clamshell.,False
7,GX010023__000099.020__000099.840.mp3,あなた's throw. 1941. 一種流行,One clamshell.,False,One clamshell.,False
8,GX010023__000099.020__000099.840.mp3,あなた's throw. 1941. 一種流行,One clamshell.,False,One clamshell.,False
9,GX010023__000099.020__000099.840.mp3,あなた's throw. 1941. 一種流行,One clamshell.,False,One clamshell.,False

'phrase'와 매칭된 전사 비율:
44.42%

'timestamp_group_phrase'와 매칭된 전사 비율:
44.42%

### 특정 키워드로 전사 결과 필터링

이제 `final_comparison_df`를 사용하여 특정 키워드를 포함하는 전사 내용을 필터링하고, 해당 클립의 메타데이터 정보를 함께 살펴볼 수 있습니다. 예를 들어, '플라스틱'이라는 단어가 언급된 전사 내용을 찾아보겠습니다.

In [ ]:
keyword_to_filter = 'plastic'

filtered_df = final_comparison_df[
    final_comparison_df['transcription_text_snippet'].str.contains(keyword_to_filter, case=False, na=False)
]

print(f"\n'{keyword_to_filter}' 키워드를 포함하는 전사 결과 (상위 10개):")
display(filtered_df[['audio_filename', 'transcription_text_snippet', 'phrase', 'category_name', 'supercategory_name']].head(10))

print(f"\n총 {len(filtered_df)}개의 전사 결과에서 '{keyword_to_filter}' 키워드가 발견되었습니다.")

'plastic' 키워드를 포함하는 전사 결과 (상위 10개):

,audio_filename,transcription_text_snippet,phrase,category_name,supercategory_name
10,GX010023__000174.060__000174.680.mp3,plastic clamshell,Clamshell.,Containers #1/Clamshells,Plastics
16,GX010023__000300.420__000304.740.mp3,"Number one, clamshell. Oh, black plastic.",number one clamshell oh black plastic,Containers #1/Clamshells,Plastics
17,GX010023__000300.420__000304.740.mp3,"Number one, clamshell. Oh, black plastic.",number one clamshell oh black plastic,Containers #1/Clamshells,Plastics
452,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
453,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
454,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
455,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
456,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
457,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics
458,GX010023__000304.740__000308.200.mp3,"Oh, black plastic. Mm-hmm. Black plastic.",black plastic,Black Plastic Containers,Plastics

총 179개의 전사 결과에서 'plastic' 키워드가 발견되었습니다.

이러한 방식으로 전사 결과를 기존 메타데이터와 비교하고 필터링할 수 있습니다. 추가적으로 어떤 종류의 비교나 분석을 원하시나요?

## `timestamp_groups_df` 정보 상세

In [ ]:
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'

try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    print("Timestamp Groups DataFrame (first 5 rows):")
    display(timestamp_groups_df.head())

    print("\nDataFrame Information:")
    display(timestamp_groups_df.info())

    print("\nDescriptive Statistics:")
    display(timestamp_groups_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{timestamp_groups_csv_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Timestamp Groups DataFrame (first 5 rows):

,gx_name,source_meta2_path,begin_time,end_time,duration_seconds,meta2_phrase,transcript_phrases,category_names,supercategory_names,number_of_meta2_rows,number_of_unique_frames,start_frame,end_frame,frame_names,raw_video_path,transcript_json_path,clip_path,clip_status
0,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,10.62,12.02,1.40,Unnumbered.,NaN,Other Unnumbered Containers & Fragments,Plastics,10,7,2,10,000002 | 000003 | 000005 | 000007 | 000008 | 000009 | 000010,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000010.620__000012.020.mp4,created
1,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,12.72,14.12,1.40,Clamshell.,NaN,Containers #1/Clamshells,Plastics,5,5,18,22,000018 | 000019 | 000020 | 000021 | 000022,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4,created
2,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,15.00,20.26,5.26,Number 5.,NaN,Containers #5/PP,Plastics,5,4,48,64,000048 | 000062 | 000063 | 000064,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000015.000__000020.260.mp4,created
3,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,32.46,33.50,1.04,Two color.,NaN,Containers #2 Colored,Plastics,11,7,89,95,000089 | 000090 | 000091 | 000092 | 000093 | 000094 | 000095,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000032.460__000033.500.mp4,created
4,GX010023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX010023/data/meta2.csv,46.62,47.44,0.82,Two color.,NaN,Containers #2 Colored,Plastics,6,5,97,102,000097 | 000098 | 000099 | 000100 | 000102,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX010023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX010023/GX010023__000046.620__000047.440.mp4,created

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gx_name                  463 non-null    object
 1   source_meta2_path        463 non-null    object
 2   begin_time               463 non-null    float64
 3   end_time                 463 non-null    float64
 4   duration_seconds         463 non-null    float64
 5   meta2_phrase             463 non-null    object
 6   transcript_phrases       0 non-null      float64
 7   category_names           463 non-null    object
 8   supercategory_names      463 non-null    object
 9   number_of_meta2_rows     463 non-null    int64
 10  number_of_unique_frames  463 non-null    int64
 11  start_frame              463 non-null    int64
 12  end_frame                463 non-null    int64
 13  frame_names              463 non-null    object
 14  raw_video_path           463 non-null    object
 15  transcript_json_path     0 non-null      float64
 16  clip_path                463 non-null    object
 17  clip_status              463 non-null    object
dtypes: float64(5), int64(4), object(9)
memory usage: 65.2+ KB

None

Descriptive Statistics:

,gx_name,source_meta2_path,begin_time,end_time,duration_seconds,meta2_phrase,transcript_phrases,category_names,supercategory_names,number_of_meta2_rows,number_of_unique_frames,start_frame,end_frame,frame_names,raw_video_path,transcript_json_path,clip_path,clip_status
count,463,463,463.000000,463.000000,463.000000,463,0.0,463,463,463.000000,463.000000,463.000000,463.000000,463,463,0.0,463,463
unique,6,6,NaN,NaN,NaN,156,NaN,20,1,NaN,NaN,NaN,NaN,459,6,NaN,463,1
top,GX020023,/media/jisha/E/trash_dataset/Brookhaven MRF 20250604 Preproc/Camera 1/GX020023/data/meta2.csv,NaN,NaN,NaN,Clamshell.,NaN,Other #1 Bottles,Plastics,NaN,NaN,NaN,NaN,001970 | 001971,/media/jisha/D/trash_dataset/Brookhaven MRF 20250604/Camera1/GX020023.MP4,NaN,/media/jisha/E/trash_dataset/camera1_plastics_shareable_dataset/audio_video_clips/GX030023/GX030023__000180.640__000181.240.mp4,created
freq,143,143,NaN,NaN,NaN,33,NaN,81,463,NaN,NaN,NaN,NaN,2,143,NaN,1,463
mean,NaN,NaN,539.531382,540.864190,1.332808,NaN,NaN,NaN,NaN,4.138229,3.542117,939.181425,943.161987,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,297.876017,297.925318,1.015753,NaN,NaN,NaN,NaN,3.801672,3.059627,678.553502,678.110497,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,1.320000,0.220000,NaN,NaN,NaN,NaN,1.000000,1.000000,2.000000,8.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,270.410000,271.530000,0.710000,NaN,NaN,NaN,NaN,2.000000,1.000000,351.000000,356.500000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,573.840000,577.200000,1.060000,NaN,NaN,NaN,NaN,3.000000,3.000000,845.000000,845.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,793.140000,795.170000,1.560000,NaN,NaN,NaN,NaN,6.000000,5.000000,1364.000000,1365.500000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,1023.520000,1024.600000,7.880000,NaN,NaN,NaN,NaN,32.000000,27.000000,2542.000000,2542.000000,NaN,NaN,NaN,NaN,NaN

## Whisper 전사 성능 평가

In [ ]:
import pandas as pd
import os

# Ensure db_root is defined
# In a typical Colab environment, this might already be set from an earlier cell
# If not, you might need to run the initial setup cells (e.g., drive mount, db_root definition)

# --- 1. Load meta_df (if not already in kernel state) ---
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'
try:
    meta_df = pd.read_csv(csv_file_path)
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' for meta_df was not found.")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading meta_df: {e}")

# Ensure timestamp_groups_df is loaded (if not already in kernel state)
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")

# --- Diagnostic print: Check supercategory_names in timestamp_groups_df before merge ---
print("\n--- supercategory_names in timestamp_groups_df before merge ---")
if not timestamp_groups_df.empty:
    print(timestamp_groups_df['supercategory_names'].value_counts(dropna=False))
else:
    print("timestamp_groups_df is empty.")


# --- 2. Reconstruct transcription_df from .txt files (if transcription_results not in memory) ---
transcribe_output_dir = '/content/drive/MyDrive/csire_code/transcribe/v1'

if 'transcription_results' not in globals() or not transcription_results:
    print("Reconstructing transcription_results from .txt files...")
    transcription_results = []
    for txt_filename in os.listdir(transcribe_output_dir):
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading transcription file {txt_filename}: {e}")
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results)} transcription entries.")

transcription_df = pd.DataFrame(transcription_results)

# --- 3. Re-create final_comparison_df with correct merging logic ---

# 'audio_filename'에서 clip ID를 추출 (예: 'GX010023__000012.720__000014.120.mp3' -> 'GX010023__000012.720__000014.120')
transcription_df['clip_id'] = transcription_df['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# timestamp_groups_df의 'clip_path'에서 clip ID 추출
timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)

# Merge transcription_df with timestamp_groups_df directly
# This ensures each transcription is associated with the correct clip-level metadata
# and avoids duplicating rows due to frame-level metadata in meta_df.
final_comparison_df = pd.merge(
    transcription_df,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase', # Use meta2_phrase from timestamp_groups as the primary phrase
        'supercategory_names': 'supercategory_name' # Rename for consistency
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- Diagnostic print: Check supercategory_name in final_comparison_df after merge ---
print("\n--- supercategory_name in final_comparison_df after merge ---")
if not final_comparison_df.empty:
    print(final_comparison_df['supercategory_name'].value_counts(dropna=False))
else:
    print("final_comparison_df is empty.")


# --- 4. Redefine check_keyword_match function ---
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())
    return bool(transcription_words.intersection(target_words))

# 'transcription_text_snippet'과 'phrase' 간의 일치 여부 확인
final_comparison_df['matches_meta_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# For 'timestamp_group_phrase', we'll use the same 'phrase' column for comparison
# as it originates from meta2_phrase in timestamp_groups_df.
final_comparison_df['matches_timestamp_group_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# --- 5. Performance evaluation code ---
# 전체 'phrase' 및 'timestamp_group_phrase'와의 매칭 비율 재확인
print("\n--- 전체 매칭 비율 ---")
print(f"'phrase'와 매칭된 전사 비율: {final_comparison_df['matches_meta_phrase'].sum() / len(final_comparison_df):.2%}")
print(f"'timestamp_group_phrase'와 매칭된 전사 비율: {final_comparison_df['matches_timestamp_group_phrase'].sum() / len(final_comparison_df):.2%}")

# supercategory_name별 매칭 비율 분석
print("\n--- 'supercategory_name'별 매칭 비율 (phrase) ---")
match_by_supercategory_phrase = final_comparison_df.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase)

print("\n--- 'supercategory_name'별 매칭 비율 (timestamp_group_phrase) ---")
match_by_supercategory_timestamp_phrase = final_comparison_df.groupby('supercategory_name')['matches_timestamp_group_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_timestamp_phrase)

--- supercategory_names in timestamp_groups_df before merge ---
supercategory_names
Plastics    463
Name: count, dtype: int64

--- supercategory_name in final_comparison_df after merge ---
supercategory_name
Plastics    463
Name: count, dtype: int64

--- 전체 매칭 비율 ---
'phrase'와 매칭된 전사 비율: 41.68%
'timestamp_group_phrase'와 매칭된 전사 비율: 41.68%

--- 'supercategory_name'별 매칭 비율 (phrase) ---

supercategory_name
Plastics    41.68%
Name: matches_meta_phrase, dtype: object

--- 'supercategory_name'별 매칭 비율 (timestamp_group_phrase) ---

supercategory_name
Plastics    41.68%
Name: matches_timestamp_group_phrase, dtype: object

## Whisper V2 (Large 모델) 전사 및 성능 비교

이제 Whisper 'large' 모델을 사용하여 오디오를 다시 전사하고, 이전 'base' 모델(v1)과 성능을 비교해 보겠습니다. 'large' 모델은 더 높은 정확도를 제공할 수 있지만, 전사 시간이 더 오래 걸릴 수 있습니다.

In [ ]:
# Install Whisper and other necessary libraries if they aren't already
!pip install -qqq openai-whisper

import os
import json
import pandas as pd
import whisper
from tqdm.notebook import tqdm
from datetime import datetime

# V2 전사 결과를 위한 디렉토리 설정
transcribe_output_dir_v2 = '/content/drive/MyDrive/csire_code/transcribe/v2'
manifest_output_path_v2 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v2.json'

os.makedirs(transcribe_output_dir_v2, exist_ok=True)
os.makedirs(os.path.dirname(manifest_output_path_v2), exist_ok=True)

# Ensure audio_input_dir and audio_files are defined for this section
audio_input_dir = '/content/drive/MyDrive/csire_code/audio'
audio_files = [f for f in os.listdir(audio_input_dir) if f.endswith('.mp3')]

print(f"V2 Transcription output directory: {transcribe_output_dir_v2}")
print(f"V2 Manifest output path: {manifest_output_path_v2}")
print(f"Audio input directory: {audio_input_dir}")
print(f"Found {len(audio_files)} audio files for V2 transcription.")

V2 Transcription output directory: /content/drive/MyDrive/csire_code/transcribe/v2
V2 Manifest output path: /content/drive/MyDrive/csire_code/transcribe/manifest_v2.json
Audio input directory: /content/drive/MyDrive/csire_code/audio
Found 463 audio files for V2 transcription.

In [ ]:
# Whisper 'large' 모델 로드
print("Loading Whisper 'large' model...")
model_large = whisper.load_model("large")
print("Whisper 'large' model loaded.")

transcription_results_v2 = []

# audio_input_dir은 이전 셀에서 정의되었습니다.
# audio_files는 이전 셀에서 로드되었습니다.

print(f"Found {len(audio_files)} audio files to transcribe with V2 (large model).")

# 이 과정은 시간이 오래 걸릴 수 있습니다. 백그라운드 실행을 원하시면 셀을 실행하고 다른 작업을 진행하세요.
for audio_filename in tqdm(audio_files, desc="Transcribing audio files with V2 (large)"):
    audio_file_path = os.path.join(audio_input_dir, audio_filename)
    output_txt_filename = os.path.splitext(audio_filename)[0] + '.txt'
    output_txt_path = os.path.join(transcribe_output_dir_v2, output_txt_filename)

    try:
        # 오디오 전사 (large 모델 사용)
        result = model_large.transcribe(audio_file_path)
        transcription_text = result["text"]

        # 전사 결과를 텍스트 파일로 저장
        with open(output_txt_path, 'w', encoding='utf-8') as f:
            f.write(transcription_text)

        transcription_results_v2.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': output_txt_path,
            'status': 'success',
            'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
        })
    except Exception as e:
        transcription_results_v2.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': None,
            'status': f'error: {e}',
            'transcription_text_snippet': None
        })
        print(f"Error transcribing {audio_filename} with V2: {e}")

print(f"\nCompleted transcription for {len(transcription_results_v2)} files using Whisper V2 (large).")

In [ ]:
# V2 매니페스트 파일 생성
manifest_data_v2 = {
    'run_timestamp': datetime.now().isoformat(),
    'whisper_model': 'large',
    'audio_input_directory': audio_input_dir,
    'transcription_output_directory': transcribe_output_dir_v2,
    'transcription_summary': transcription_results_v2
}

with open(manifest_output_path_v2, 'w', encoding='utf-8') as f:
    json.dump(manifest_data_v2, f, ensure_ascii=False, indent=4)

print(f"V2 Manifest file saved to: {manifest_output_path_v2}")

# V2 매니페스트 내용 일부 표시
print("\nV2 Manifest file content (first 5 entries):")
with open(manifest_output_path_v2, 'r', encoding='utf-8') as f:
    manifest_content_v2 = json.load(f)
display(pd.DataFrame(manifest_content_v2['transcription_summary']).head())

## Whisper V1 (Base) vs V2 (Large) 성능 비교

이제 Whisper 'base' 모델(v1)과 'large' 모델(v2)의 전사 성능을 'supercategory_name'별 매칭률을 기준으로 비교해 보겠습니다.

In [ ]:
import pandas as pd
import os
import json

# db_root와 timestamp_groups_df가 이전 셀에서 정의되었다고 가정합니다.
# 만약 커널 재시작 등으로 인해 정의되지 않았다면, 관련 셀들을 먼저 실행해야 합니다.

# Ensure timestamp_groups_df is loaded. This is necessary if previous cells defining it were not run.
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    # 'clip_path' 컬럼에서 clip ID 추출
    timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors

# --- V1 (Base Model) 데이터프레임 준비 ---
# transcription_results는 이미 메모리에 있다고 가정합니다.
# 만약 없다면, manifest_v1.json에서 로드하거나 .txt 파일에서 재구성합니다.
manifest_output_path_v1 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v1.json'
transcribe_output_dir_v1 = '/content/drive/MyDrive/csire_code/transcribe/v1' # Define V1 output directory

if 'transcription_results' not in globals() or not transcription_results:
    print("Reconstructing V1 transcription_results from .txt files...")
    transcription_results = []
    for txt_filename in os.listdir(transcribe_output_dir_v1):
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir_v1, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading transcription file {txt_filename}: {e}")
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results)} V1 transcription entries.")

transcription_df_v1 = pd.DataFrame(transcription_results)
transcription_df_v1['clip_id'] = transcription_df_v1['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# timestamp_groups_df는 이 셀 상단에서 로드되었습니다.
# 'clip_id' 컬럼도 생성되었습니다.

final_comparison_df_v1 = pd.merge(
    transcription_df_v1,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- V2 (Large Model) 데이터프레임 준비 ---
# transcription_results_v2는 이미 메모리에 있다고 가정합니다.
# 만약 없다면, manifest_v2.json에서 로드하거나 .txt 파일에서 재구성합니다.
manifest_output_path_v2 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v2.json'
transcribe_output_dir_v2 = '/content/drive/MyDrive/csire_code/transcribe/v2' # Define V2 output directory

if 'transcription_results_v2' not in globals() or not transcription_results_v2:
    print("Reconstructing V2 transcription_results from .txt files...")
    transcription_results_v2 = []
    for txt_filename in os.listdir(transcribe_output_dir_v2):
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir_v2, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results_v2.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading V2 transcription file {txt_filename}: {e}")
                transcription_results_v2.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results_v2)} V2 transcription entries.")

transcription_df_v2 = pd.DataFrame(transcription_results_v2)
transcription_df_v2['clip_id'] = transcription_df_v2['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

final_comparison_df_v2 = pd.merge(
    transcription_df_v2,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- 키워드 매칭 함수 (이전 셀에서 정의된 것을 다시 정의하여 확실히 사용 가능하게 함) ---
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())
    return bool(transcription_words.intersection(target_words))

# V1 데이터프레임에 매칭 결과 추가
final_comparison_df_v1['matches_meta_phrase'] = final_comparison_df_v1.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)
final_comparison_df_v1['matches_timestamp_group_phrase'] = final_comparison_df_v1.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# V2 데이터프레임에 매칭 결과 추가
final_comparison_df_v2['matches_meta_phrase'] = final_comparison_df_v2.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)
final_comparison_df_v2['matches_timestamp_group_phrase'] = final_comparison_df_v2.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

print("데이터프레임 준비 완료.")

In [ ]:
print("\n--- Overall Matching Rate Comparison (using map_transcript_to_category) ---")

# V1 (Base Model) - Apply map_transcript_to_category
final_comparison_df_v1['predicted_category'] = final_comparison_df_v1['transcription_text_snippet'].apply(map_transcript_to_category)
success_rate_v1 = (final_comparison_df_v1['predicted_category'] == final_comparison_df_v1['category_names']).mean() * 100
print(f"V1 (Base) 'map_transcript_to_category' success rate: {success_rate_v1:.2f}%")

# V2 (Large Model) - Apply map_transcript_to_category
final_comparison_df_v2['predicted_category'] = final_comparison_df_v2['transcription_text_snippet'].apply(map_transcript_to_category)
success_rate_v2 = (final_comparison_df_v2['predicted_category'] == final_comparison_df_v2['category_names']).mean() * 100
print(f"V2 (Large) 'map_transcript_to_category' success rate: {success_rate_v2:.2f}%")

print("\n--- 'supercategory_name'별 매칭 비율 (map_transcript_to_category) 비교 ---")
print("V1 (Base) 모델:")
match_by_supercategory_v1 = final_comparison_df_v1.groupby('supercategory_name')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_supercategory_v1)

print("V2 (Large) 모델:")
match_by_supercategory_v2 = final_comparison_df_v2.groupby('supercategory_name')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_supercategory_v2)


print("\n--- 'category_name'별 매칭 비율 (map_transcript_to_category) 비교 ---")
print("V1 (Base) 모델:")
match_by_category_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v1)

print("V2 (Large) 모델:")
match_by_category_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v2)

## Whisper V1 (Base) vs V2 (Large) Success Rate Comparison

In [ ]:
print("\n--- Overall Matching Rate Comparison ---")
print(f"V1 (Base) 'phrase' matching rate: {final_comparison_df_v1['matches_meta_phrase'].sum() / len(final_comparison_df_v1):.2%}")
print(f"V2 (Large) 'phrase' matching rate: {final_comparison_df_v2['matches_meta_phrase'].sum() / len(final_comparison_df_v2):.2%}")

print("\n--- 'supercategory_name' Matching Rate (V1 Base) ---")
match_by_supercategory_phrase_v1 = final_comparison_df_v1.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase_v1)

print("\n--- 'supercategory_name' Matching Rate (V2 Large) ---")
match_by_supercategory_phrase_v2 = final_comparison_df_v2.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase_v2)

## Phrase Value Counts per Category

In [ ]:
phrase_counts_by_category = timestamp_groups_df.groupby('category_names')['meta2_phrase'].nunique()
for category in timestamp_groups_df['category_names'].unique():
    print(f"\n--- Category: {category}: {phrase_counts_by_category[category]} ---")
    category_phrases = timestamp_groups_df[timestamp_groups_df['category_names'] == category]['meta2_phrase'].value_counts().to_dict()
    for phrase, count in category_phrases.items():
        print(f"  '{phrase}': {count}")

### Validating `map_transcript_to_category` function using `timestamp_groups_df['meta2_phrase']`

We will compare the `predicted_category` with the actual `category_name`.

### Using Sentence Embeddings for Category Assignment

To improve the classification of transcriptions, we will now use a pretrained sentence embedding model to encode the `meta2_phrase` phrases and then use cosine similarity to find the most similar category for each transcription.

In [ ]:
# Install the sentence-transformers library
!pip install -qqq sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import numpy as np

print("Sentence-transformers and other libraries imported.")

First, we will load a pretrained sentence embedding model. We'll use `all-MiniLM-L6-v2` which is efficient and performs well for semantic similarity tasks.

In [ ]:
# Load a pretrained sentence embedding model
print("Loading SentenceTransformer model...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("SentenceTransformer model loaded.")

# Prepare the reference phrases and their corresponding categories from timestamp_groups_df
# Ensure timestamp_groups_df is loaded from previous cells

# Filter out NaN phrases and drop duplicates to get unique phrase-category mappings
reference_phrases_df = timestamp_groups_df[['meta2_phrase', 'category_names']].dropna().drop_duplicates().reset_index(drop=True)

# Encode all unique meta2_phrases to create reference embeddings
print(f"Encoding {len(reference_phrases_df)} unique reference phrases...")
reference_phrase_embeddings = embedding_model.encode(reference_phrases_df['meta2_phrase'].tolist(), convert_to_tensor=True)
print("Reference phrases encoded.")

# Create a dictionary for quick lookup of category names
phrase_to_category_map = reference_phrases_df.set_index('meta2_phrase')['category_names'].to_dict()

print("Reference phrases and categories prepared.")

Now, we define a function that takes a transcription, encodes it, compares it with the reference phrase embeddings using cosine similarity, and assigns the category of the most similar reference phrase.

In [ ]:
def assign_category_with_embedding(transcription_text):
    if pd.isna(transcription_text) or not transcription_text.strip():
        return "Unknown"

    # Encode the input transcription text
    transcription_embedding = embedding_model.encode(transcription_text, convert_to_tensor=True)

    # Compute cosine similarities between the transcription and all reference phrases
    cosine_scores = util.cos_sim(transcription_embedding, reference_phrase_embeddings)[0]

    # Get the index of the most similar reference phrase
    best_match_idx = np.argmax(cosine_scores.cpu().numpy())

    # Get the corresponding reference phrase and its category
    best_match_phrase = reference_phrases_df.loc[best_match_idx, 'meta2_phrase']
    predicted_category = phrase_to_category_map.get(best_match_phrase, "Unknown")

    return predicted_category

print("Embedding-based category assignment function defined.")

Next, we will apply this new `assign_category_with_embedding` function to both V1 (Base) and V2 (Large) transcription results to get embedding-based predicted categories. Then we will compare their performance with the actual `category_names`.

In [ ]:
def map_transcript_to_category(transcript_text):
    if pd.isna(transcript_text): return "Unknown"
    text = transcript_text.lower()

    # --- 1. Exact Matches (Highest Priority) ---
    # These are highly specific phrases that should map to a single, confident category.
    if text == "non -deposit garbage bag":
        return "Non-Deposit" # Fix for common misclassification (Actual: Non-Deposit, Predicted: Garbage Bags)
    if text == "dissolt.":
        return "Deposit #1 Bottles"
    if text == "fly plastic.":
        return "Black Plastic Containers"
    if text == "under posit one down to positive":
        return "Non-Deposit"
    if text == "no." or text == "no":
        return "Containers #1/Clamshells"
    if text == "one deposit." or text == "one deposit":
        return "Deposit #1 Bottles"
    if "other one" in text or "lid" in text:
        return "Containers #1/Clamshells"
    if "five" in text or "5" in text:
        return "Containers #5/PP"
    if text == "unnumbered.":
        return "Other Unnumbered Containers & Fragments"
    if text == "other plastic.":
        return "Other Plastics"
    if "two" in text and "color" in text:
        return "Containers #2 Colored"
    if text == "number one.":
        return "Deposit #1 Bottles" # Assuming "number one." alone usually means Deposit #1 Bottles based on phrase_counts_by_category

    # --- 2. Highly Specific Keyword-Based Rules (Higher Priority) ---
    # NEW RULE: If both "one" and "non" are present, classify as "Other #1 Bottles"
    if ("one" in text or "1" in text) and "non" in text:
        return "Other #1 Bottles"

    if "non" in text and "deposit" in text:
        return "Non-Deposit"

    # These cover phrases containing strong category indicators.
    if "garbage bag" in text:
        return "Garbage Bags"

    if "black" in text:
        return "Black Plastic Containers"

    if "clam" in text and "shell" in text:
        return "Containers #1/Clamshells"

    if "two natural" in text:
        return "Containers #2 Natural"
    if "two color" in text or "two colored" in text:
        return "Containers #2 Colored"

    # --- 3. Number-Based Rules (Medium Priority) ---
    if "three" in text or "3" in text or "seven" in text or "7" in text or "four" in text or "4" in text or "six" in text or "6" in text:
        return "Containers #3-7 (Not #5)"
    if "five" in text or "5" in text:
        return "Containers #5/PP"

    # --- 4. Deposit/Non-Deposit & Number #1 Rules (Careful Prioritization) ---
    # This section is critical for distinguishing similar phrases.
    if "number one" in text:
        if "deposit" in text:
            return "Deposit #1 Bottles"
        # The 'non -deposit' case here for 'number one' will be caught by the new 'one' and 'non' rule if 'non' is also present
        return "Other #1 Bottles" # If 'number one' but no deposit/non-deposit specifier (and not caught by 'one' and 'non' rule)

    if "deposit" in text:
        return "Deposit #1 Bottles"


    # --- 5. Other Generic Category Keywords (Lower Priority) ---
    if "plastic film" in text or "film plastic" in text or "film" in text:
        return "Other Plastic Film"

    if "other plastic" in text:
        return "Other Plastics"

    if "unnumbered" in text:
        return "Other Unnumbered Containers & Fragments"

    if "bulky rigid" in text:
        return "Other Rigid/Bulky Plastics"

    if "if you find numbers" in text:
        return "Other Unnumbered Containers & Fragments"

    if "plastic" in text:
        return "Plastic"

    if "one" in text:
        return "Containers #1/Clamshells"
    # Default return if no rules match
    return "Unknown"

# Apply the mapping function to timestamp_groups_df['meta2_phrase']
timestamp_groups_df['predicted_category_from_phrase'] = timestamp_groups_df['meta2_phrase'].apply(map_transcript_to_category)

# Calculate the success rate
success_rate_from_phrase = (timestamp_groups_df['predicted_category_from_phrase'] == timestamp_groups_df['category_names']).mean() * 100

print(f"Success Rate of `map_transcript_to_category` using `timestamp_groups_df['meta2_phrase']`: {success_rate_from_phrase:.2f}%")

# Identify misclassified entries
incorrect_classifications = timestamp_groups_df[
    timestamp_groups_df['predicted_category_from_phrase'] != timestamp_groups_df['category_names']
]

# Group by actual category, predicted category, and phrase to find common misclassification patterns
misclassification_patterns = incorrect_classifications.groupby(['meta2_phrase', 'category_names', 'predicted_category_from_phrase']).size().reset_index(name='count')

# Sort by count to see the most frequent misclassifications
misclassification_patterns = misclassification_patterns.sort_values(by='count', ascending=False)

print("\nMost Frequent Misclassification Patterns (Top 20):")
display(misclassification_patterns.head(30))

print(f"\nTotal misclassified entries: {len(incorrect_classifications)}")

In [ ]:
# Apply the new embedding-based classification function to V1 and V2 dataframes
print("Applying embedding-based classification to V1 transcripts...")
final_comparison_df_v1['predicted_category_embedding'] = final_comparison_df_v1['transcription_text_snippet'].apply(assign_category_with_embedding)

print("Applying embedding-based classification to V2 transcripts...")
final_comparison_df_v2['predicted_category_embedding'] = final_comparison_df_v2['transcription_text_snippet'].apply(assign_category_with_embedding)

# Calculate success rates for V1 and V2 using embedding-based prediction
success_rate_v1_embedding = (final_comparison_df_v1['predicted_category_embedding'] == final_comparison_df_v1['category_names']).mean() * 100
success_rate_v2_embedding = (final_comparison_df_v2['predicted_category_embedding'] == final_comparison_df_v2['category_names']).mean() * 100

print(f"\nOverall embedding-based success rate for V1 (Base): {success_rate_v1_embedding:.2f}%")
print(f"Overall embedding-based success rate for V2 (Large): {success_rate_v2_embedding:.2f}%")


# Apply the mapping function to timestamp_groups_df['meta2_phrase']
timestamp_embedding['predicted_category_from_phrase_embedding'] = timestamp_groups_df['meta2_phrase'].apply(assign_category_with_embedding)

# Calculate the success rate
success_rate_from_phrase = (timestamp_embedding['predicted_category_from_phrase_embedding'] == timestamp_groups_df['category_names']).mean() * 100

print(f"Success Rate of `embedding-based classification` using `timestamp_groups_df['meta2_phrase']`: {success_rate_from_phrase:.2f}%")



# Category-wise success rates for V1 (embedding)
print("\nCategory-wise embedding success rate for V1 (Base):")
match_by_category_v1_embedding = final_comparison_df_v1.groupby('category_names')['predicted_category_embedding'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v1_embedding)

# Category-wise success rates for V2 (embedding)
print("\nCategory-wise embedding success rate for V2 (Large):")
match_by_category_v2_embedding = final_comparison_df_v2.groupby('category_names')['predicted_category_embedding'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v2_embedding)

# Combine into a summary DataFrame for easy comparison
comparison_embedding_success_rates = pd.DataFrame({
    'V1_Embedding_Success_Rate': match_by_category_v1_embedding,
    'V2_Embedding_Success_Rate': match_by_category_v2_embedding
}).reset_index()

# Merge with the existing final_comparison_summary_with_overall
final_comparison_summary_with_all_methods = pd.merge(
    final_comparison_summary_with_overall,
    comparison_embedding_success_rates,
    on='category_names',
    how='left'
)

# Update Overall row for embedding success rates
overall_summary_row_embedding = pd.DataFrame([{
    'category_names': 'Overall',
    'V1_Embedding_Success_Rate': f'{success_rate_v1_embedding:.2f}%',
    'V2_Embedding_Success_Rate': f'{success_rate_v2_embedding:.2f}%'
}])

# Find and update the 'Overall' row
overall_index = final_comparison_summary_with_all_methods[final_comparison_summary_with_all_methods['category_names'] == 'Overall'].index
if not overall_index.empty:
    for col in overall_summary_row_embedding.columns:
        if col != 'category_names':
            final_comparison_summary_with_all_methods.loc[overall_index, col] = overall_summary_row_embedding.loc[0, col]

print("\nCombined Category-wise Success Rates (All Methods):")
display(final_comparison_summary_with_all_methods.sort_values(by='total_clips', ascending=False))

In [ ]:
# Calculate success rates for V1 by category_name
success_by_category_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_v1.rename(columns={'predicted_category': 'predicted_category_v1_success_rate'}, inplace=True)

# Calculate success rates for V2 by category_name
success_by_category_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_v2.rename(columns={'predicted_category': 'predicted_category_v2_success_rate'}, inplace=True)

# Calculate success rates for 'predicted_category_from_phrase' (ground truth phrase mapping) using timestamp_groups_df
success_by_category_from_phrase = timestamp_groups_df.groupby('category_names')['predicted_category_from_phrase'].apply(
    lambda x: (x == timestamp_groups_df.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_from_phrase.rename(columns={'predicted_category_from_phrase': 'predicted_category_from_phrase_success_rate'}, inplace=True)

# Merge all success rates into a single DataFrame
comparison_success_rates = pd.merge(success_by_category_v1, success_by_category_v2, on='category_names', how='outer')
comparison_success_rates = pd.merge(comparison_success_rates, success_by_category_from_phrase, on='category_names', how='outer')

import os

# Ensure timestamp_groups_df has 'clip_id' column for this calculation
# This line might be redundant if the column is created earlier and guaranteed to persist,
# but adding it here ensures the calculation always works.
if 'clip_id' not in timestamp_groups_df.columns:
    timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)

total_clips_by_category = timestamp_groups_df.groupby('category_names')['clip_id'].nunique().reset_index()
total_clips_by_category.rename(columns={'clip_id': 'total_clips'}, inplace=True)

final_comparison_summary = pd.merge(comparison_success_rates, total_clips_by_category, on='category_names', how='outer')

overall_success_v1 = success_rate_v1
overall_success_v2 = success_rate_v2
overall_success_from_phrase = success_rate_from_phrase

overall_total_clips = total_clips_by_category['total_clips'].sum()

overall_summary_row = pd.DataFrame([{
    'category_names': 'Overall',
    'predicted_category_v1_success_rate': overall_success_v1,
    'predicted_category_v2_success_rate': overall_success_v2,
    'predicted_category_from_phrase_success_rate': overall_success_from_phrase,
    'total_clips': overall_total_clips
}])

final_comparison_summary_with_overall = pd.concat([final_comparison_summary, overall_summary_row], ignore_index=True)

print("\nCombined Category-wise Success Rates and Total Clips (with Overall Summary):")
display(final_comparison_summary_with_overall.sort_values(by='total_clips', ascending=False).round(2))